# Generated by Django 4.1.1 on 2022-10-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hillbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flyingsite',
            name='slug',
        ),
    ]
